spring:
  datasource:
    url: jdbc:mysql://localhost:3306/malaquias_fv
    username: root
    password: 123mfv
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
app:
  base-url: /api/v1
